services:
  ros:
    build: .
    image: ros_dev:${IMAGE_TAG:-latest} 
    container_name: ros_dev
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./rosOC:/home/ros/rosOC
      - ./ros_ws:/home/ros/ros_ws
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]