services:
  ros:
    build: .
    image: ros_dev:latest
    container_name: ros_dev_env
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # 変更点：個別のワークスペースをマウントする
      # カレントディレクトリにあるrosOCを、コンテナ内の/home/ros/rosOCにマウント
      - ./rosOC:/home/ros/rosOC
      # カレントディレクトリにあるros_wsを、コンテナ内の/home/ros/ros_wsにマウント
      - ./ros_ws:/home/ros/ros_ws
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]